version: "3.8"

services:
  mysql:
    image: mysql:8.0
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:6379"

  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.21.0
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    restart: unless-stopped

volumes:
  mysql_data:
